Installer pod annotations
pegasystems/pega-helm-charts pull request #201
Opened 2020-10-26 18:38 UTC by misterdorito

Allow annotations for the installer pod.

2020-10-26 18:53 UTC, khick77 approved these changes

2020-10-26 18:55 UTC, APegaDavis approved these changes

2020-10-27 04:58 UTC, kishorv10 approved these changes

2020-10-27 12:34 UTC, dcasavant approved these changes

2020-10-27 16:10 UTC, taz-pega-work requested changes
after you make one small change, I think we can ship it!

2020-10-27 16:59 UTC, taz-pega-work approved these changes

2020-10-27 18:01 UTC, merged