BUG-630370 - Logger for repackaged hazelcast Cluster Logs
pegasystems/pega-helm-charts pull request #250
Opened 2021-02-19 17:36 UTC by vikasmviky

2021-02-24 09:53 UTC, kishorv10 commented on charts/pega/charts/installer/config/prlog4j2.xml
> +		<RollingRandomAccessFile  name="CLUSTER" fileName="${sys:pega.logdir}/PegaCLUSTER.log" filePattern="${sys:pega.logdir}/PegaCLUSTER-%d{MM-dd-yyyy}-%i.log.gz">
fileName and filePattern values might need to computed in other way with installer. Check other appender configuration [here](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/charts/installer/config/prlog4j2.xml#L13)

2021-02-24 09:54 UTC, kishorv10 requested changes

2021-02-24 09:54 UTC, kishorv10 commented on charts/pega/charts/installer/config/prlog4j2.xml
> +				<Pattern>%d [%20.20t] [%20.20X{tenantid}] [%20.20X{app}] (%30.30c{3}) %-5p %X{stack} %X{userid} - %m%n</Pattern>
Same with the Pattern, better to be in synch with other appender patterns. Tenantid may not make sense during installer.

2021-03-16 06:29 UTC, MadhuriArugula approved these changes

2021-03-16 09:29 UTC, NekhilKotha approved these changes

2021-03-16 09:39 UTC, saikarthik528 approved these changes

2021-03-16 09:52 UTC, kishorv10 approved these changes

2021-03-16 09:53 UTC, kishorv10 commented
@vikasmviky Can you please a github issue for this bug and link to the PR.

2021-03-16 11:44 UTC, merged