US-410084-2:Deployment changes for Client Cloud SRS-ES AuthN
pegasystems/pega-helm-charts pull request #285
Opened 2021-05-17 13:23 UTC by Anand-Kotamsetti

1)Added Basic Authentication and AWS IAM Role authentication support for SRS

2021-05-19 13:58 UTC, taz-pega-work reviewed
I added a little more clarity to a few of your comments. In general these are helpful comments and ready to go from my perspective.

2021-05-19 13:58 UTC, taz-pega-work commented on charts/backingservices/values.yaml
> +    # If externally managed Elasticsearch cluster is authenticated with Basic Authentication then please set below srs.srsStorage.basicAuthentication's srs.srsStorage.basicAuthentication.username and
To configure authentication for the externally managed Elasticsearch cluster to use Basic Authentication then uncomment and add the parameters, srs.srsStorage.basicAuthentication.username and srs.srsStorage.basicAuthentication.password

To configure authentication for the externally managed Elasticsearch cluster to use an AWS IAM Role then uncomment and add the parameters, srs.srsStorage.awsIAM and srs.srsStorage.awsIAM.region

2021-05-19 13:58 UTC, taz-pega-work commented on charts/backingservices/values.yaml
> +  #Extra Environmental Variables for elasticsearch basic authentication , Values are read from Secrets
Use this section to include additional, supported environmental variables for Elasticsearch basic authentication. The parameter values can be read from a specified secrets file.

2021-05-24 10:32 UTC, MadhuriArugula requested changes

2021-05-24 10:32 UTC, MadhuriArugula commented on charts/backingservices/charts/srs/templates/_helpers.tpl
> +    {{- else }}
Can we have this else block inline to `if` to get a clear understanding of code.

2021-05-24 10:32 UTC, MadhuriArugula commented on charts/backingservices/charts/srs/templates/_helpers.tpl
> +        {{- fail "Please disable/comment Values.srsStorage.basicAuthentication or Values.srsStorage.awsIAM when '.Values.srsStorage.provisionInternalESCluster' is true" | quote  }}
Is this condition reachable? If not, can we remove this `else` statement?

2021-05-25 10:19 UTC, MadhuriArugula approved these changes

2021-05-25 10:23 UTC, Saurabh-16 approved these changes

2021-06-03 06:14 UTC, Anand-Kotamsetti commented on charts/backingservices/values.yaml
> +#      region: "AWS_ELASTICSEARCH_REGION"
Thanks for feedback,
We do have similar flow to identify the configuration value in SRS. As this configuration value is internal to SRS we are not expecting this values to be passed as input by client.

2021-06-03 12:29 UTC, taz-pega-work reviewed
The in-line guidance has inconsistent punctuation and is hard to read, especially hte IAM role-bases settings...don't add possessive "'s" to a parameter name...it's very confusing ;-)  ...I added suggestions to clarify instructions for your users.

2021-06-03 12:29 UTC, taz-pega-work commented on charts/backingservices/values.yaml
> +    # Currently the elasticsearch connection is supported with Basic Authentication  and AWS IAM Role based Authentication .
The elasticsearch connection supports two authentication methods: basic authentication or AWS IAM role-based authentication.

2021-06-03 12:29 UTC, taz-pega-work commented on charts/backingservices/values.yaml
> +#     To configure authentication for the externally managed Elasticsearch cluster to use Basic Authentication then uncomment
To configure basic authentication to your externally-managed Elasticsearch cluster,  uncomment and add the parameter details: srs.srsStorage.basicAuthentication.username and srs.srsStorage.basicAuthentication.password

2021-06-03 12:29 UTC, taz-pega-work commented on charts/backingservices/values.yaml
> +#     To configure authentication for the externally managed Elasticsearch cluster to use an AWS IAM Role then uncomment and
To configure AWS IAM role-based authentication to your externally-managed Elasticsearch cluster, uncomment and add the parameter details:  srs.srsStorage.awsIAM and its associated region, srs.srsStorage.awsIAM.region

2021-06-03 12:29 UTC, taz-pega-work commented on charts/backingservices/values.yaml
> +#     set `requireInternetAccess` to true when the elasticsearch domain is outside of the Kubernetes cluster network  and is available over internet
To configure either authentication method, when the elasticsearch domain requires an open internet connection, uncomment to set this parameter to "true".

2021-06-04 11:57 UTC, taz-pega-work commented
documentation content is good!

2021-06-07 10:05 UTC, kishorv10 approved these changes

2021-06-08 06:01 UTC, pega-kshev approved these changes

2021-06-08 13:25 UTC, vanga approved these changes

2021-06-08 13:39 UTC, pega-kshev approved these changes

2021-06-08 13:40 UTC, pega-kshev approved these changes

2021-06-08 13:41 UTC, pega-kshev approved these changes

2021-06-08 16:32 UTC, taz-pega-work approved these changes
looks good. thanks for making changes in the runbooks!

2021-06-09 08:40 UTC, merged