US-522126 Adding OAUTH_PUBLIC_KEY_URL in deployment parameters
pegasystems/pega-helm-charts pull request #529
Opened 2023-02-27 12:59 UTC by chandra-kalavakuri

As SRS supports IDP based authentication/authorization, in CMC, client can now enable authentication between Infinity and SRS by setting `srs.srsRuntime.env.AuthEnabled ` flag to `true` and configure `OAUTH_PUBLIC_KEY_URL` config with IDP's public key url

2023-02-27 15:48 UTC, taz-pega-work requested changes
please update the wording for OAuthPublicKeyURL across the different yaml files as suggested.

2023-03-07 10:05 UTC, Anand-Kotamsetti approved these changes
LGTM

2023-03-07 12:45 UTC, chandra-kalavakuri commented on charts/backingservices/charts/srs/README.md
> +      # Set the value for parameter 'OAuthPublicKeyURL' when AuthEnabled is true.
Thanks for the quick feedback Taz 👍 
I have updated the same. can you please review the latest PR :)

2023-03-09 06:49 UTC, chandra-kalavakuri commented
@kingakowalska1 , please review the PR

2023-03-09 07:15 UTC, bhowd1 approved these changes

2023-03-09 16:39 UTC, petejo commented
Please update the description and describe the purpose of this commit

2023-03-09 17:10 UTC, taz-pega-work approved these changes
looks great @chandra-kalavakuri. thank you!

2023-03-10 04:15 UTC, chandra-kalavakuri commented
> Please update the description and describe the purpose of this commit

done. added description for the PR

2023-03-10 08:11 UTC, merged