added TLS support for openshift Route
pegasystems/pega-helm-charts pull request #575
Opened 2023-06-05 06:04 UTC by pega-sagas1

2023-06-05 13:33 UTC, taz-pega-work reviewed
why is this change only available in values-large.yaml and not in the other two Pega

2023-06-05 13:33 UTC, taz-pega-work commented on charts/pega/values-large.yaml
> +          # for enabling TLS in Openshift Route as Reencrypt, add certificate, key and CaCertificate PEM or crt format.
for enabling TLS in Openshift Route as Reencrypt, add certificate, key and CaCertificate PEM or crt format.

can we update this wording to be less jargony? maybe not all clients would understand as written. As a start, I suggest>
For Openshift, enable TLS in Route do this [whatever Reencrypt specifically means in this context], and add your certificate, the corresponding key using the appropriate .pem or .crt format.

2023-06-05 13:34 UTC, taz-pega-work commented on charts/pega/values-large.yaml
> +          # for enabling TLS in Openshift Route as Reencrypt, add certificate, key and CaCertificate PEM or crt format.
also wondering why this is only in large-values.yaml and not in the basic values.yaml file.

2023-06-06 07:59 UTC, pega-sagas1 commented
hi @taz-pega-work, Please review.

2023-06-06 20:30 UTC, taz-pega-work requested changes
Still need to improve sentence structure. Did I capture the gist of the requirements?

2023-06-06 20:30 UTC, taz-pega-work commented on charts/pega/values-large.yaml
> +          # For Openshift, to enable TLS, the termination policy would be reencrypt rather than edge, and we can add our certificate, the corresponding key using the appropriate .pem or .crt format a
can we refine this??
For Openshift, Pega  deployments enable TLS to secure the connection from the browser to the router by creating the route using reencrypt termination policy. Add your certificate, the corresponding key using the appropriate .pem or .crt format and specify a CA certificate to validate the endpoint certificate.

2023-06-08 13:29 UTC, taz-pega-work approved these changes
thanks for collaborating!

2023-06-12 15:01 UTC, taz-pega-work approved these changes
thanks for collaborating

2023-06-19 10:19 UTC, MadhuriArugula approved these changes

2023-06-21 09:56 UTC, merged