ISSUE-655 Constellation messaging chart
pegasystems/pega-helm-charts pull request #656
Opened 2023-10-23 21:30 UTC by maracle6

fixes #655

2023-11-08 10:12 UTC, kingakowalska1 approved these changes
Hello,

Because we are currently in the process of reworking the Constellation documentation to be available directly on docs.pega.com, but the work is still in progress, I approve of the readme as it is for now, but once the Constellation documentation is fully published on docs.pega.com, some changes will need to be made to the readme (for example, links to more information, etc.) I will take care of the changes myself.

Thanks for the great work in preparing the Helm chart.

Kinga

2023-12-11 10:13 UTC, MadhuriArugula commented
@maracle6 Is this PR still waiting on merge?

2024-01-05 18:50 UTC, nikhilparmar86 requested changes

2024-01-08 17:18 UTC, maracle6 commented on charts/backingservices/charts/constellation-messaging/README.md
> +Once the service routing (with TLS) is set up, configure the Pega Infinity ConstellationMessageSvcHostPath DSS to your service URL (e.g.  http://yourhostname.com/c11n-messaging).
@nikhilparmar86 Thanks for catching that, I updated it

2024-01-24 18:38 UTC, npjohnson637 approved these changes

2024-01-24 18:39 UTC, npjohnson637 commented
sorry for the delay

2024-02-29 10:21 UTC, MadhuriArugula commented
@nikhilparmar86 Can you provide your approvals on the requested changes to proceed with the merge?

2024-03-05 15:36 UTC, nikhilparmar86 approved these changes

2024-04-01 15:38 UTC, merged