Added support for custom envFrom
pegasystems/pega-helm-charts pull request #673
Opened 2023-11-27 10:29 UTC by MathijsFra

Added support for .custom.envFrom so for example you can reference to secrets when further templating context.xml

2023-11-27 13:36 UTC, taz-pega-work reviewed
is there any documentation for how a client will use this additional setting? I would think we need additional details in the pega readme.

2023-11-27 15:30 UTC, MathijsFra commented
Hi @taz-pega-work i just added some documentation in the Readme

2023-11-27 16:09 UTC, taz-pega-work approved these changes
looks great! thanks @MathijsFra !!!!!

2024-02-29 10:07 UTC, MadhuriArugula approved these changes

2024-02-29 10:07 UTC, MadhuriArugula commented
@MathijsFra Can you please add unit tests for the new feature.

2024-02-29 10:12 UTC, MadhuriArugula requested changes
Unit tests for the new feature are required.

2024-04-23 11:02 UTC, kishorv10 commented
@MathijsFra Can you create github issue for the requirement and link it here? Provide the required details about the current issue/use case and other details?

2025-02-05 12:55 UTC, closed without merging