ISSUE-711: add support for securityContext to SRS
pegasystems/pega-helm-charts pull request #712
Opened 2024-02-23 10:08 UTC by konire

Fixes https://github.com/pegasystems/pega-helm-charts/issues/711

2024-04-25 10:17 UTC, kishorv10 commented
@konire Can you fix the lint issues?

2024-04-25 11:27 UTC, dekke046 commented
@kishorv10 @konire ,

Can you please have a look how to incoporate this on a global level for each chart?
So not only for the backingservices, but also for pega and addons?

That gives the possibily to have it all in a universal way for the values.yaml files for each chart.

Secondly it is important to also properly propagate it to the helpers, like `wait-for-pegasearch` and part of base images like  `pega-web-tomcat`, `search`

Thanks!

2024-06-19 10:57 UTC, kishorv10 approved these changes

2024-06-19 11:28 UTC, kishorv10 commented
@reddy-srinivas @ravitejamekapega Can you review the PR?

2024-06-21 08:52 UTC, MadhuriArugula requested changes

2024-06-21 08:52 UTC, MadhuriArugula commented on charts/backingservices/charts/srs/templates/srsservice_deployment.yaml
> +          securityContext:
do we need the securityContext key if `Values.srsRuntime.securityContext` is not provided in values.yaml? 
Can you please add unit tests for the same?

2024-09-30 10:01 UTC, kishorv10 commented
#806 provide the required capabilities looking out of this PR. Probably this can be closed.

2025-01-03 06:52 UTC, closed without merging

2025-01-03 06:52 UTC, kishorv10 commented
Closing the PR as same is addressed in #806