Add GKE support for Constellation and Constellation Messaging
pegasystems/pega-helm-charts pull request #770
Opened 2024-06-05 16:04 UTC by alemax22

This PL addresses the issues #748 and #749.
In particular we:
- added the support of GKE to the constellation and constellation messaging helm subchart in the backingservices chart;
- added the liveness and readiness probes to the constellation messaging subchart in the backingservices chart;
- updated the default values of the constellation and constellation messaging subchart;
- updated the documentation of the constellation and constellation messaging subcharts;
- created unit tests for the GKE support of constellation and constellation messaging subchart;
- created unit tests for the ingresses;
- aligned values file of constellation and constellation messaging subchart to the values file of the main Pega chart, in this way their keys reflect the ones of the Pega chart;
- documented deprecated keys and maintained backward compatibility with old keys while introducing the new ones.

2024-07-30 11:58 UTC, nikhilparmar86 requested changes

2024-07-30 11:58 UTC, nikhilparmar86 commented on charts/backingservices/charts/constellation-messaging/templates/messaging-deployment.yaml
> +      - name: {{ include "backingservicesRegistrySecret" ( dict "root" .Values "defaultname" "constellation" ) }}
@alemax22 , Could you please update defaultname to "constellation-messaging"

2024-07-30 11:58 UTC, nikhilparmar86 commented on charts/backingservices/charts/constellation-messaging/values.yaml
> -  domain:
@alemax22 , Could you add "enabled" to true similar to constellation ? as used in https://github.com/pegasystems/pega-helm-charts/pull/770/files#diff-a986186add6bda5f00bf46ded3f50ba492c52674874c7e608ee0744c30f081d0R4

2024-07-30 11:58 UTC, nikhilparmar86 commented on charts/backingservices/charts/constellation-messaging/templates/_messaging-registry-secret.tpl
> +{{- define "messagingRegistryCredentialsSecretTemplate" }}
@alemax22 , Could you include this for messaging charts like  charts/backingservices/charts/constellation/templates/clln-registry-secret.yaml ?

2024-07-30 12:05 UTC, nikhilparmar86 requested changes

2024-07-30 12:05 UTC, nikhilparmar86 commented on charts/backingservices/charts/constellation-messaging/templates/messaging-deployment.yaml
> +        - path={{ .Values.urlPath }}
@alemax22  Could you please update the path to urlPath similar to constellation deployment, like : urlPath={{ .Values.urlPath }} ?

2024-07-30 14:38 UTC, alemax22 commented
@nikhilparmar86 the last commit resolves all your requests

2024-07-31 14:18 UTC, nikhilparmar86 approved these changes

2024-08-13 03:31 UTC, anuds20 approved these changes

2024-08-14 05:04 UTC, kishorv10 approved these changes

2024-08-16 13:21 UTC, merged